version: "3.3"

services:
  node:
    container_name: cc-log-api
    build:
      context: .
      # args:
      #   - NODE_ENV=development
    tty: true
    environment:
      - NODE_ENV=production
    ports:
      - "8345:8345"
    volumes:
      - ./app/src:/app/src:delegated

    # command: yarn run docker:build:prod
    command: yarn run docker:dev

  mongo:
    container_name: cc-log-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-express:
    container_name: cc-log-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

volumes:
  mongo-data:

networks:
  default:
    external:
      name: chichi-network
